#!/usr/bin/env python3
"""Generates src/sim/PlayerState.gen.hpp from Geode's GeometryDash.bro.

GD's practice checkpoints do not restore every field of PlayerObject, so a level
restored from a checkpoint can behave differently from the run that created it.
The generated snapshot copies every plain-value field of PlayerObject (numbers,
flags, points, and containers of those), which the simulations restore after the
game's own checkpoint load.

Usage: gen_player_state.py path/to/bindings/2.2081/GeometryDash.bro
"""
import re
import sys
from pathlib import Path

KEEP_TYPES = {
    "bool", "int", "float", "double", "unsigned char", "unsigned int", "short",
    "cocos2d::CCPoint",
    "gd::unordered_set<int>", "gd::map<int, bool>", "gd::vector<float>",
    "gd::unordered_map<int, GJPointDouble>", "gd::unordered_map<int, GameObject*>",
}
# Visual-only or owned by the level rather than the player.
SKIP_FIELDS = set()

def main():
    bro = Path(sys.argv[1]).read_text()
    start = bro.index("\nclass PlayerObject ")
    end = bro.index("\n}", start)
    body = bro[start:end]
    fields = []
    for line in body.splitlines():
        m = re.match(r"^\s+([A-Za-z_:][A-Za-z0-9_:<>, \*]*?)\s+(m_[A-Za-z0-9_]+);\s*(//.*)?$", line)
        if not m:
            continue
        type_, name = m.group(1).strip(), m.group(2)
        if type_ in KEEP_TYPES and name not in SKIP_FIELDS:
            fields.append((type_, name))

    out = []
    out.append("// Generated by tools/gen_player_state.py from Geode's GD 2.2081 bindings. Do not edit.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <Geode/Geode.hpp>")
    out.append("")
    out.append(f"// {len(fields)} plain-value fields of PlayerObject, plus its position and rotation.")
    out.append("struct PlayerStateSnapshot {")
    out.append("    cocos2d::CCPoint position;")
    out.append("    float rotation = 0.f;")
    for t, n in fields:
        out.append(f"    {t} {n} {{}};")
    out.append("")
    out.append("    void save(PlayerObject* p) {")
    out.append("        position = p->getPosition();")
    out.append("        rotation = p->getRotation();")
    for _, n in fields:
        out.append(f"        {n} = p->{n};")
    out.append("    }")
    out.append("")
    out.append("    void apply(PlayerObject* p) const {")
    for _, n in fields:
        out.append(f"        p->{n} = {n};")
    out.append("        p->setPosition(position);")
    out.append("        p->setRotation(rotation);")
    out.append("    }")
    out.append("};")
    out.append("")
    Path(__file__).resolve().parent.parent.joinpath("src/sim/PlayerState.gen.hpp").write_text("\n".join(out))
    print(f"{len(fields)} fields")

main()
