name: Build DLL
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B build -A Win32
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xinput9_1_0-dll
          path: build/Release/xinput9_1_0.dll
